spring:
  application:
    name: mall-portal
  profiles:
    active: dev #默认为开发环境
  datasource:
    url: jdbc:mysql://39.101.136.95/miaosha?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 39.101.136.95
    password: 123456
    port: 6379
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头